# Generated by Django 4.1.6 on 2023-02-13 11:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0002_alter_account_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('receiving_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='transfers.account')),
                ('sender_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='transfers.account')),
            ],
        ),
    ]
