# Generated by Django 4.1.6 on 2023-02-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0003_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='starting_balance',
            field=models.IntegerField(default=0),
        ),
    ]
