# Generated by Django 4.1.6 on 2023-02-13 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0004_transfer_starting_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='starting_balance',
            new_name='samount',
        ),
    ]
