# Generated by Django 4.1.6 on 2023-02-13 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0005_rename_starting_balance_transfer_samount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='samount',
            new_name='amount',
        ),
    ]
